### ISSUE TITLE
Unexpected token on "npm run watch"

### ISSUE THREAD

**Issue by lbayerlein** [mrliptontea/PurpleMine2#100]
Hi,

I have installed your theme, but it does not work, to compile scss files to css files. On my server, I did a git checkout. As documented, I created a new file called _custom-variables.css in the scss directory and included it on top on applications.scss. Unfortunately any change is not converted and placed into the public directory.

This error comes up, if I start the "npm run watch" and do some changes to the file:
![2019-03-26_19-16](https://user-images.githubusercontent.com/2928812/55023999-41753a80-4ffe-11e9-9245-bddb183bdb0c.png)

If you need further informations, please let me know.

Thanks very much

**Comment by mrliptontea** [comment]
Hi,

Yeah, grunt-sass doesn't convey errors very well, so in order to debug sass it's better to run node-sass directly, like this:

```shell
./node_modules/.bin/node-sass --output stylesheets src/sass/application.scss
```

This should tell you what and where exactly the problem is.

**Comment by lbayerlein** [comment]
Hi,

thanks for your quick reply. If I run this command, everything works fine. There is no error message at all. It tells me, that it is writing the css file correctly. So for me it is fixed. Should I close this issue or do you want to debug?

**Comment by mrliptontea** [comment]
Hmm I just read the message from your screenshot more carefully - it says it's `Loading "sass.js" tasks` causes an error, not an .scss file.

Can you verify node version you use? Run `node --version`, it should be at least 8.

Either way it seems like an issue with your installation or grunt-sass package, hope you find the cause.
