### ISSUE TITLE
gantt tool tip bug

### ISSUE THREAD

**Issue by kare1133** [mrliptontea/PurpleMine2#101]
![image](https://user-images.githubusercontent.com/49189937/55392046-77be3700-5575-11e9-8329-7dc555a78c7c.png)

redmine version : redmine 4.0.2
Browser : chrome

**Comment by ZerooCool** [comment]
Hi, i come for the same bug.
For the moment, i can display 2 or 3 months before the task, there is space to display the info bubble.

It's still embarrassing.

**Comment by ZerooCool** [comment]
From this css file : /themes/PurpleMine2/stylesheets/application.css

```
tr > td:last-child .tooltip .tip {
    right: 2px; /* Remove this line for test, with Firefox */
    left: auto;
}
```
