### ISSUE TITLE
You can not copy the text of an error from the error summary table

### ISSUE THREAD

**Issue by ZerooCool** [mrliptontea/PurpleMine2#103]
You can not copy the text of an error from the error summary table.

From /projects/name
Look the table, and, test if you can copy the name from a issue. I can't.

I need open the link.
Then, i can copy the name from a issue.

**Comment by mrliptontea** [comment]
I can't copy any text from a single issue row because it becomes selected when I release mouse button but that's Redmine's JavaScript. The default theme has the same behaviour.

However, it does work in Redmine 3.3 and earlier, so you'd have to bring this issue with Redmine.
