### ISSUE TITLE
Change favicon.ico

### ISSUE THREAD

**Issue by donrulo2014** [mrliptontea/PurpleMine2#110]
Hi,

I'm running `npm run watch`, and changing the favicon.ico, however it doesn't show anything.

I've also done this without the `npm run watch` with no success.

Is there a way to change it?

**Comment by mrliptontea** [comment]
Hi,

Try restarting Redmine, it should append the timestamp based on the favicon.ico file's modification date to the URL, so the browser would know it changed.

Hope this helps.

**Comment by donrulo2014** [comment]
Thnx!
