### ISSUE TITLE
A lot of free space inside ticket next to associated revisions

### ISSUE THREAD

**Issue by Nan000** [mrliptontea/PurpleMine2#111]
Hi all,

I really love this theme but I noticed that there is a lot of free space inside the ticket next to associated revisions. In the original theme this is filled up with the comment section below. Is this intended?

![2019-05-20 22_45_50-Task #66_ Check the possibility to reduce the overall camera length to 85 mm - P](https://user-images.githubusercontent.com/34923690/58051083-89719300-7b51-11e9-8079-53b0ee5641ba.png)

**Comment by mrliptontea** [comment]
Hi,

No, this is not intended, should look like below. What browser do you use? What plugins do you have installed? Can you inspect with dev tools and see what could be causing this?

![revisions](https://user-images.githubusercontent.com/3495587/58051932-5b895000-7b4b-11e9-832d-61ae6987f1ac.PNG)

**Comment by Nan000** [comment]
Hi,

thanks for the quick response. I've checked the page source but I'm not sure what to search for. In the first screenshot below I've selected the over all content node and in the second one the issue-changeset node.

My environment is set up as follows:

Web-browser: Chrome Version 74.0.3729.131 (Offizieller Build) (64-Bit) / I double checked with Internet Explorer -> Same issue here

Redmine Setup
![image](https://user-images.githubusercontent.com/34923690/58208556-3e888480-7ce5-11e9-8a4b-c8695ef316ea.png)


![2019-05-22 22_51_07-Window](https://user-images.githubusercontent.com/34923690/58208053-4267d700-7ce4-11e9-9652-b2ba09fd0a9f.png)

![2019-05-22 22_55_53-](https://user-images.githubusercontent.com/34923690/58208370-e3569200-7ce4-11e9-908e-fbd5286905ac.png)

**Comment by mrliptontea** [comment]
Aha! I found the cause - this happens when a user selects **Display comments** - _In reverse chronological order_ option in /my/account.

The same layout issue then happens with the default theme. This is because with reversed order the contextual menu is also displayed above the comment history, as defined [in the template](https://github.com/redmine/redmine/blob/d646ec22cfd9b905688be010bf16c429bf31718f/app/views/issues/show.html.erb#L130-L139).

Sorry but I'm afraid I can't fix this.

**Comment by Nan000** [comment]
Hi, thanks a lot for the quick analysis. But this has worked in the past. Do you think this is a bug or intended by the Redmine developers?

**Comment by mrliptontea** [comment]
Yeah, I can think of no reason why would you need to reverse also the order of elements on the page, and since it affects all themes this should be raised with Redmine team.

**Comment by Nan000** [comment]
I've raised a ticket to Redmine. Lets see if they fix it ;-)

[31438 Associated revisions block not places next to history](https://www.redmine.org/issues/31438)

**Thanks for your great support and keep developing this awesome theme !!**
