### ISSUE TITLE
[Suggestion] Red color for Task overdue date

### ISSUE THREAD

**Issue by lamhaison** [mrliptontea/PurpleMine2#115]
First of all, Thank you so much for what you have done when You created a awesome theme for Redmine. My co-worker is so impressive when I use this theme on our Redmine.

When I access to my home page. When I have a task overdue date. We can have a improve by coloring red that task at Due date filed. Here are my screenshoot for my suggestion.
Im my page
![My idea](https://i.ibb.co/kxRtbLC/my-suggession.png)
In Issue filter pages
![My Idea](https://i.ibb.co/56Qg9xJ/sugesstion-1-in-filter-issue-page.png)
Because today is 2019/06/02 and There are a task with due date is 2019/05/30(the task with ID is 24). Users will have a notice about that task than other tasks.

 
Thank you

**Comment by mrliptontea** [comment]
Hi,

I applied this suggestion, check out the latest release. In fact, I noticed this was included in the default theme and in the process, I added few added styles which were introduced in the Redmine since I last checked for additions.

**Comment by lamhaison** [comment]
@mrliptontea . I already updated the changing. It worked perfectly. Thank you
