### ISSUE TITLE
My Page blocks overflow when accessing via in mobile device

### ISSUE THREAD

**Issue by pasqualedante** [mrliptontea/PurpleMine2#120]
I have 2 blocks in in My Page: one aligned to left and another aligned to right.
When accessing with a mobile device, the two blocks overflows as shown in attached screenshot.

<img width="540" alt="Screenshot_2019-06-11-08-00-15-062_org mozilla firefox_beta" src="https://user-images.githubusercontent.com/813690/59251625-8c304700-8c2a-11e9-800c-05e5c49c9a07.png">

**Comment by mrliptontea** [comment]
Hmm, this doesn't quite look like the theme - top navigation should match the theme color and I can see there are some conflicting styles.

This is how it looks for me, these two lists are side-by-side on the desktop:
![image](https://user-images.githubusercontent.com/3495587/59295302-4059be00-8c7b-11e9-8989-38111a5f9952.png)

I suspect a plugin might be responsible?
