### ISSUE TITLE
Cant open ticket detail page from gantt tool

### ISSUE THREAD

**Issue by Suica5555** [mrliptontea/PurpleMine2#123]
Hello.

cant open ticket detail page from gantt tool.
![cap](https://user-images.githubusercontent.com/25079447/59407515-6488dc80-8dec-11e9-9757-ccdcbeec7e63.PNG)

**Comment by mrliptontea** [comment]
Hi,

From what I have checked clicking there doesn't do anything, you must click on the ticket ID (that orange part in your example).
