### ISSUE TITLE
Support the issue-id plugin?

### ISSUE THREAD

**Issue by kay54068** [mrliptontea/PurpleMine2#124]
How can support the issue-id plugin?
The issue id field of the problem does not change color when I use the issue-id plugin.
![圖片](https://user-images.githubusercontent.com/3054544/59448740-61b3d900-8e38-11e9-8cbe-e6194f3a1a2f.png)

ref:
http://projects.andriylesyuk.com/projects/issue-id/wiki

**Comment by mrliptontea** [comment]
While the plugin does not seem to be actively maintained, I thought it's rather useful so I added support for it 👍
