### ISSUE TITLE
Report css view when using Redmine Issue Templates plugin

### ISSUE THREAD

**Issue by lamhaison** [mrliptontea/PurpleMine2#128]
I am using **Redmine Issue Template** Plugin(https://github.com/akiko-pusu/redmine_issue_templates) for creating template when I create a new issue.

But when I create a new issue from global setting or from a specific project. It works well if I use default theme or other thems but with our themes, the css is not working well like that
There are some issue like that
  - You can see that In Button Template list, the Icon was behind the Template List tex
  - Cancel Button is not be in the correct position(next to Create Button) in creating template form.

* Global template settings
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/global_template_1.png?raw=true)
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/project_template_1.png?raw=true)

* Project template settings
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/project_template_2.png?raw=true)
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/global_template_2.png?raw=true)
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/setting_template_for_a_project.png?raw=true)

If you want any more information. Please comment I will provide what you want. 
Thank you

**Comment by mrliptontea** [comment]
Hi,

I found that it's the plugin that does a few things in its own way rather than following Redmine's style. I created a pull request to the original plugin. Meanwhile, you could use my fork or create your own and merge my changes to it.

**Comment by akiko-pusu** [comment]
Hi, @mrliptontea. I'm an author of that plugin. I deeply appreciate that you handled this issue.
I'm going to confirm your PR as soon as possible!

**Comment by lamhaison** [comment]
@mrliptontea . After getting the new pull request to my local environment.
I check the result. When I already have a template issue, when I access to edit form. It seems not good like that.

![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/redmine_issue_template_edit_template_setting_in_project.png?raw=true)
If you want any test, please ping me. I am appreciate to do that.

**Comment by mrliptontea** [comment]
I pushed some further fixes for these.

**Comment by lamhaison** [comment]
ok. Let me check :).

**Comment by lamhaison** [comment]
It work well

* edit global template form
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/redmine_issue_temlate_work_well_with_golbal_edit_template.png?raw=true)
* Edit note and issue template in project settings
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/redmine_issue_template_work_well_edit_note_project_setting_template.png?raw=true)
![](https://github.com/lamhaison/report-issue-images/blob/master/redmine_PurpleMine2/redmine_issue_template_work_well_edit_setting_project.png?raw=true)
