### ISSUE TITLE
Assignee list overflowing

### ISSUE THREAD

**Issue by pbystrov** [mrliptontea/PurpleMine2#129]
Hello,

Assignee list overflowing for subtasks while displaying parent task details.

![image](https://user-images.githubusercontent.com/15250610/60422191-25cc9200-9bf4-11e9-8aee-bc3579c88cdc.png)

Checklist's plus sign gets broken after that if I try to edit the same task.

![image](https://user-images.githubusercontent.com/15250610/60422893-a0e27800-9bf5-11e9-81c4-f7cfc152cdbb.png)

Checklist's plus sign is ok during edit if overflow wasn't triggered.
```
Environment:
  Redmine version                4.0.0.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  additionals                    2.0.21-master
  clipboard_image_paste          1.13
  redmine_agile                  1.4.11
  redmine_checklists             3.1.16
  redmine_custom_workflows       1.0.0
  redmine_favorite_projects      2.1.0
  redmine_percent_done           1.1.0
  redmine_theme_changer          0.4.0
  redmineup_tags                 2.0.6
```

**Comment by mrliptontea** [comment]
Hi,

I wish I could help, but I can't replicate this, and it seems like a plugin issue. `redmine_checklists` does, in fact, override `#context-menu.checklist-menu li.folder ul { overflow: visible; }` which would cause overflowing but normally this dropdown shouldn't have the `checklist-menu` class.
