### ISSUE TITLE
Expand and collapse projects overview

### ISSUE THREAD

**Issue by kay54068** [mrliptontea/PurpleMine2#131]
HI @mrliptontea,

The current projects overview tree looks messy. how can I implementation the expand and collapse feature?

![圖片](https://user-images.githubusercontent.com/3054544/61471284-1780c300-a9b5-11e9-9377-c79ed52600e8.png)

**Comment by mrliptontea** [comment]
Hi,

This would be outside of the scope of a theme and something a plugin should do. A short search led me to an old feature request https://www.redmine.org/issues/7982 and this plugin: https://github.com/anton-sergeev/redmine_subproject_collapse.
