### ISSUE TITLE
Projects page view error

### ISSUE THREAD

**Issue by taisik** [mrliptontea/PurpleMine2#138]
Hi! 

PurpleMine2 2.8.0 is set.
Why is it being viewed in a small box instead of being full screen on the 'projects' page?  Redmine installation environment is as below. 

Thank you.

![CD4996C5-2F45-4CAE-90A0-EC5512D7F036](https://user-images.githubusercontent.com/53636985/63673549-7ee52a80-c81f-11e9-8472-f659d31c660d.jpeg)
![F882486B-9037-45EB-BEB7-7A2C6EF6AFA6](https://user-images.githubusercontent.com/53636985/63673553-7f7dc100-c81f-11e9-9931-73998e2f413f.jpeg)

**Comment by taisik** [comment]
> Hi!
> 
> PurpleMine2 2.8.0 is set.
> Why is it being viewed in a small box instead of being full screen on the 'projects' page? Redmine installation environment is as below.
> 
> Thank you.
> 
> ![CD4996C5-2F45-4CAE-90A0-EC5512D7F036](https://user-images.githubusercontent.com/53636985/63673549-7ee52a80-c81f-11e9-8472-f659d31c660d.jpeg)
> ![F882486B-9037-45EB-BEB7-7A2C6EF6AFA6](https://user-images.githubusercontent.com/53636985/63673553-7f7dc100-c81f-11e9-9931-73998e2f413f.jpeg)

**Comment by taisik** [comment]
It wasn't an error ^^

The following source has been modified and customized.

`/src/sass/components/_elements.scss`
<img width="892" alt="스크린샷 2019-08-27 오후 1 08 50" src="https://user-images.githubusercontent.com/53636985/63740816-82cf8600-c8cd-11e9-8759-1d8bfd1f26dc.png">
Anyway thank you very much!

**Comment by mrliptontea** [comment]
Hi,

Glad you found a solution. This layout was intended however, as you have seen, it may not fit every use case. As an alternative, you could try following the [customization guide](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it) and set `$use-project-tiles: false;` in your `_custom-variables.scss`.

**Comment by taisik** [comment]
Oh! This is what I want. Thank you again.
