### ISSUE TITLE
Is it possible to change some colors?

### ISSUE THREAD

**Issue by thecrazy** [mrliptontea/PurpleMine2#140]
**I know its called purple but sometimes it would be nice if it were:** Amaranth Amber Amethyst Apricot Aquamarine Azure Baby blue Beige Black Blue Blue-green Blue-violet Blush Bronze Brown Burgundy Byzantium Carmine Cerise Cerulean Champagne Chartreuse green Chocolate Cobalt blue Coffee Copper Coral Crimson Cyan Desert sand Electric blue Emerald Erin Gold Gray Green Harlequin Indigo Ivory Jade Jungle green Lavender Lemon Lilac Lime Magenta Magenta rose Maroon Mauve Navy blue Ochre Olive Orange Orange-red Orchid Peach Pear Periwinkle Persian blue Pink Plum Prussian blue Puce Purple Raspberry Red Red-violet Rose Ruby Salmon Sangria Sapphire Scarlet Silver Slate gray Spring bud Spring green Tan Taupe Teal Turquoise Ultramarine Violet Viridian White Yellow.

**Comment by thecrazy** [comment]
The real reason would be able to change the main color theme per project.

**Comment by mrliptontea** [comment]
It's possible, for example you could create copies of the theme under different names and follow the [How to customize it](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it) guide to create different colour variants. I also found this simple patch https://www.redmine.org/issues/233 that allows to set a theme per project.
