### ISSUE TITLE
In redmine 4.1.0, it's difficult do download a file in File tab

### ISSUE THREAD

**Issue by pasqualedante** [mrliptontea/PurpleMine2#152]
I'm experiencing s strange behavior: with purplemine2 theme applied and redmine 4.1.0 running, I cannot download a file from project _File_ tab: to start the operation I need to click multiple time on download icon. With default theme applied I haven't this issue.
Thanks in advance.

**Comment by mrliptontea** [comment]
I am unable to replicate the issue in Redmine 4.1.0 in Chrome or Firefox. Do you still experience this? If yes, please send the information from `/admin/info` page.

**Comment by mrliptontea** [comment]
I'm closing this. If you are still experiencing the issue, please don't hesitate to reply.

**Comment by pasqualedante** [comment]
Hi @mrliptontea, sorry for the big delay : I attach here a video to show the steps to reproduce the issue. It seems related to row highlight feature. I can download the file only if I'm exactly on the download icon.
Thanks in advance.

![issue-in-action](https://user-images.githubusercontent.com/813690/82749575-5c7e3e80-9daa-11ea-9940-acc7d3768c52.gif)

**Comment by mrliptontea** [comment]
Hi @pasqualedante

Now I see what you mean. Can you update the theme and check if this is still an issue? I think this was addressed for #177.

**Comment by pasqualedante** [comment]
> 
> 
> Hi @pasqualedante
> 
> Now I see what you mean. Can you update the theme and check if this is still an issue? I think this was addressed for #177.

Yep, you are right! Thanks.

**Comment by mrliptontea** [comment]
Awesome! 🎉
