### ISSUE TITLE
JS Code block is really hard to see

### ISSUE THREAD

**Issue by rockmandash** [mrliptontea/PurpleMine2#156]
![image](https://user-images.githubusercontent.com/7580792/75420619-59bea980-5973-11ea-9cc9-1d245dc1be94.png)

**Comment by mrliptontea** [comment]
That's how it looks for me:
![redmine_3040_issues_5_issue_count=10 issue_position=7 next_issue_id=4 prev_issue_id=6 (1)](https://user-images.githubusercontent.com/3495587/76707549-ee513780-66e7-11ea-8f50-649e110ffcb4.png)

Are you using any customizations or plugins?

**Comment by rockmandash** [comment]
I overlapped my own theme, sorry.
