### ISSUE TITLE
Text hover is really hard to see

### ISSUE THREAD

**Issue by rockmandash** [mrliptontea/PurpleMine2#157]
![image](https://user-images.githubusercontent.com/7580792/75420647-6d6a1000-5973-11ea-944e-d0776323dfa3.png)

**Comment by mrliptontea** [comment]
There is no hover colour in theme's CSS https://github.com/mrliptontea/PurpleMine2/blob/57a60673a79f442a221b7ae8f6bf5cc4a7373f5c/src/sass/components/_top.scss#L331-L336

This style must be coming from somewhere else.

**Comment by rockmandash** [comment]
I overlapped my own theme, sorry.
