### ISSUE TITLE
How to make theme blue with right-sidebar?

### ISSUE THREAD

**Issue by etoosamoe** [mrliptontea/PurpleMine2#158]
Hello.
After i installed this great theme it was blue with right side-bar:
![image](https://user-images.githubusercontent.com/38806450/75544076-46bfde00-5a34-11ea-9122-2d7cd3707bae.png)

Then I tried to edit some settings, and had to install node.js, after that theme appeared Purple and sidebar moved to left.
![image](https://user-images.githubusercontent.com/38806450/75544141-6820ca00-5a34-11ea-884e-d489e4298dc5.png)

How can I revert it to that nice blue color? 
Actually, my attempts to edit _custom-variables were unsuccesfull. I tried to edit bg. color to blue and wiki-line-height to 1.0, and wiki font size to 14.. can you help me with advice how to do that?

**Comment by mrliptontea** [comment]
By default, the theme should like on the second screenshot, with purple colour and sidebar on the left. I don't know how more to help you other than pointing to the [customization instructions](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it).

You should add a line
```scss
@import "custom-variables";
```

Before this line here: https://github.com/mrliptontea/PurpleMine2/blob/0282ba6695177061da0612d8195d5c29d57135f7/src/sass/application.scss#L1

Your `src/sass/_custom-variables.scss` should contain the following to achieve what you want:

```scss
$sidebar-position: right;
$brand-primary: #455B9D;
```

Then run `npm run build` in the terminal and you should see the output like this:

```shell
$ npm run build

> purplemine@ build /var/redmine/public/themes/PurpleMine2
> grunt

Running "sass:theme" (sass) task

Running "sass:plugins" (sass) task

Running "postcss:all" (postcss) task
>> 14 processed stylesheets created.

Running "uglify:theme" (uglify) task
>> 1 file created 13.19 kB → 6.84 kB

Done.
```

Lastly, you might need to do a hard refresh in the browser for the changes to be picked up.

Hope this helps.

**Comment by mrliptontea** [comment]
Closing this. Please feel free to reply if you need more help.
