### ISSUE TITLE
Issue Custom Field of type Long Text not displaying properly

### ISSUE THREAD

**Issue by acosonic** [mrliptontea/PurpleMine2#159]
Multiple lines don't display correctly, seems confusing on view issue page.

Text should be on the right side, vertically aligned with first line.

![purplemineproblem](https://user-images.githubusercontent.com/862015/75571083-cb245800-5a58-11ea-9990-05a3c7fe3a62.png)

**Comment by mrliptontea** [comment]
Please see the latest changes on master branch. This layout is a bit tricky, I did best I could.
