### ISSUE TITLE
Plugin checklist menu item are text while on white background, which is unreadable

### ISSUE THREAD

**Issue by kalumkalac** [mrliptontea/PurpleMine2#160]
Hello,

I use the [checklist plugin from RedmineUP](https://www.redmineup.com/pages/fr/plugins/checklists). When you create a new issue, as the title says, text is white as well as background. Hovering make the text visible. See the image:

![image](https://user-images.githubusercontent.com/16705147/75791977-a3d9cd80-5d6d-11ea-8b40-be9fcb292cf1.png)

The class involved seems to be:

```
<li class="ui-menu-item" id="ui-id-5" tabindex="-1" role="menuitem">
```

Redmine 4.1.0 with latest version of PurpleMine.

Do you need more information ?

You can download the light version of the plugin from their website if you want to test.

Thanks.

**Comment by mrliptontea** [comment]
The light version doesn't seem to have this dropdown menu or I don't know to open it - how do you do it?

**Comment by kalumkalac** [comment]
Oh, you are right, the light version does not have the template feature. You can then use their demo redmine instance (Live preview link on the same web page), but it obviously does not contain the PurpleMine2 theme.

Will that be enough to try to debug it ? I may also be able to up a redmine instance with the plugin + the theme if needed.

I understand not beeing able to test by yourself may be a hassle.

I may also try to contact them since its a paid plugin.

**Comment by mrliptontea** [comment]
@kalumkalac I think I've got it, can you please check the branch `issue-160-checklist-menu-hover` and PR #163 for a potential fix?

**Comment by kalumkalac** [comment]
Amazing job, it works perfect.

![image](https://user-images.githubusercontent.com/16705147/78564559-e71bd600-781c-11ea-9ea0-358d9f58a202.png)
