### ISSUE TITLE
Default responsive theme fallback

### ISSUE THREAD

**Issue by Campano** [mrliptontea/PurpleMine2#164]
The theme doesn't seem to handle responsiveness very well

![j4c6m5lZ7i](https://user-images.githubusercontent.com/1384759/77598431-128bf000-6f02-11ea-881d-25cf12ecd74b.gif)

It would be nice to deactivate the fallback to default theme for a start, and then think about testing / adapting it for narrow screens.

- Firefox 74.0
- Redmine 4.1.0
- PurpleMine2 - master 24/03/20

Looks like #26 

_PS: kudos for the great work_

**Comment by mrliptontea** [comment]
The responsive bit comes from a separate stylesheet that PurpleMine tries to override - but this only works if theme's folder is named exactly `PurpleMine2` (this is presumably case-insensitive): https://github.com/mrliptontea/PurpleMine2/blob/57a60673a79f442a221b7ae8f6bf5cc4a7373f5c/src/sass/components/_responsive.scss#L7

I'm going to see if I can make it more generic.

**Comment by mrliptontea** [comment]
I was testing this and just noticed that this class is applied based on the default theme in the settings, but it may be different if you use a plugin that allows users to override their theme.
