### ISSUE TITLE
Does this include a Kanban feature?

### ISSUE THREAD

**Issue by Thegoodseller** [mrliptontea/PurpleMine2#173]
Hey, 

This looks awesome, just wanted to see if it had a Kanban feature?

Thanks

**Comment by mrliptontea** [comment]
Hi,

This project only includes a theme (CSS and a bit of JavaScript) for Redmine https://www.redmine.org/, which is the project management tool.

Redmine by default does not include any Kanban board functionality, but there are plugins that can add this feature. A very popular one would be Redmine Agile https://www.redmineup.com/pages/plugins/agile.
