### ISSUE TITLE
Can not edit comment when link to redmineID#note-xx

### ISSUE THREAD

**Issue by annguyenthienit** [mrliptontea/PurpleMine2#175]
Hi Author,

- Thanks for your theme. Currently, I found a bug on latest version as below. Can you hep me to check it again?

*Steps to Reproduce:* 
Step 1: I login into the project
Step 2: I copied link have note after same as below:
https://mydomain.com/redmine/issues/55422#note-14
Step 3: I sent it to my member to update this comment

*Actual Result:* 
My member can not edit this note when press button [Edit]

*Expected Result:* 
Can edit this note.

*Additional Regression:*
You can refer this image to clarify
![2020-04-09 11-07-41 AM](https://user-images.githubusercontent.com/2218557/78857079-9b527200-7a52-11ea-84c1-7975c44c5e33.jpg)

**Comment by annguyenthienit** [comment]
I just checked on CSS file. I think the problem at here:

"journal>div:target::before"

I removed attribute: context=""

**Comment by mrliptontea** [comment]
Thank you for spotting this, should be fixed now!

**Comment by annguyenthienit** [comment]
Thanks for your fixing. I just asked my team checked it again. This problem has fixed.
