### ISSUE TITLE
Edit Timelog issue

### ISSUE THREAD

**Issue by akshaya-rane** [mrliptontea/PurpleMine2#177]
Hi Team,

We are experiencing a problem accessing the option to edit Time log entries. Please see the attached file for more explanation. We tried upgrading the theme to the latest version still, the issue persists. 

![ezgif com-optimize](https://user-images.githubusercontent.com/11537877/79111313-ea254200-7d99-11ea-8431-3ce6e5537029.gif)

Kindly take a look.

**Comment by mrliptontea** [comment]
Thank you for spotting this - indeed this was a weird one but should be now fixed.
