### ISSUE TITLE
redmine_wysiwyg_editor plugin Full screen mode UI layout error 

### ISSUE THREAD

**Issue by kay54068** [mrliptontea/PurpleMine2#179]
Hi @mihaikelemen  ,
I have install "redmine_wysiwyg_editor" plugin , I get some UI layout error when use the Full screen function.
How can fix it?
[default theme]
![Video_2020-04-15_005620](https://user-images.githubusercontent.com/3054544/79252876-e89c6c80-7eb4-11ea-9ea7-c046421047ea.gif)

[PurpleMine2 theme]
![Video_2020-04-15_005509](https://user-images.githubusercontent.com/3054544/79252999-1b466500-7eb5-11ea-9d32-d9653c7c5067.gif)
ref:
https://github.com/taqueci/redmine_wysiwyg_editor

**Comment by mrliptontea** [comment]
Should be fixed now.
