### ISSUE TITLE
Sidebar hidden by default

### ISSUE THREAD

**Issue by lublasco** [mrliptontea/PurpleMine2#18]
Hi!

How can I achieve that sidebar is hidden by default and only appears if the user wants to show it?

Thanks in advance for your help.

**Comment by mrliptontea** [comment]
If you hide the sidebar, the setting will be stored in localStorage so that it should stay hidden until you toggle it back. Besides that, there is no possibility to make hidden by default.

Currently, I don't see the necessity for this feature, but you can try to convince me :wink:

**Comment by lublasco** [comment]
No worries. Thanks a lot for a nice theme!

**Comment by mrliptontea** [comment]
Thank you for your appreciation :grinning:
