### ISSUE TITLE
Page sidebar highlight current Wiki Item (use redmine_wiki_page_tree plugin) 

### ISSUE THREAD

**Issue by kay54068** [mrliptontea/PurpleMine2#182]
Hi @mrliptontea ,
carry on #121 issue ,  how can add page sidebar highlight current Wiki Item feature  such as this image ?

![圖片](https://user-images.githubusercontent.com/3054544/79587315-f5170400-8104-11ea-9e48-7fc19c0898cc.png)

**Comment by mrliptontea** [comment]
Hi,

Unfortunately, it can't be done because the plugin does not add any special class or anything to the link of the displayed page, so there is no way to apply special CSS to it.
