### ISSUE TITLE
Simple priority style needed

### ISSUE THREAD

**Issue by yurmala** [mrliptontea/PurpleMine2#183]
Is it possible to make simple priority style liked pic?
![image](https://user-images.githubusercontent.com/9638475/79687456-09b3e300-8250-11ea-98d1-5ebdb47220e3.png)

**Comment by mrliptontea** [comment]
Is the solution from #186 enough?

**Comment by yurmala** [comment]
Dear mrliptontea, Yes. Thanks! 
Be healthy!

**Comment by mrliptontea** [comment]
> Dear mrliptontea, Yes. Thanks!
> Be healthy!

Awesome!
Thanks, stay safe!
