### ISSUE TITLE
Highlighting issues priority on the list and on the issue page?

### ISSUE THREAD

**Issue by yurmala** [mrliptontea/PurpleMine2#186]
It seems to me that the whole issue of background red should be? But in fact this is not.
![image](https://user-images.githubusercontent.com/9638475/80214974-63e3e800-8644-11ea-91e0-972a90db9d44.png)
In the old version of the theme it worked.
![image](https://user-images.githubusercontent.com/9638475/80215588-698dfd80-8645-11ea-88ae-524e4250494f.png)

**Comment by mrliptontea** [comment]
Hi,

I just pushed a change 36000bd02c5fe856ece1b16e304ea910b4e0e1ff that restores `$color-priorities` variable, which by default is set to `false`, but when set to true it will color the whole issue row background with a color corresponding to its priority.

If you enable it you may also want to adjust the borders in the table. So after following the  [customization steps](https://github.com/mrliptontea/PurpleMine2#how-to-customize-it), put the following in your `_custom_variables.scss` and run `npm run build`:

```scss
$color-priorities:              true;
$table-list-header-border:      0 0 2px;
$table-list-item-border:        0 0 1px;
```

Now, to explain why it's not like that anymore (by default) - there were two reasons why I removed it:

1. As highlighted in [v2.0](https://github.com/mrliptontea/PurpleMine2/releases/tag/v2.0) release, it wasn't good for accessibility - some background-to-text contrasts were too low and using just colors could be problematic for people with color blindness.
2. I felt there were too many colors on the page.

**Comment by Rebellion720** [comment]
Hello;

I have purplemine version 2.16.2 and I have set the $color-priorities variable: true !default; and the task priority colors do not appear, why could it be?

Regards
