### ISSUE TITLE
RedmineUP plugins: highlight glitch for issue edit form

### ISSUE THREAD

**Issue by yurmala** [mrliptontea/PurpleMine2#187]
While using REDMINEUP plugins (https://www.redmineup.com/pages/plugins/) there are highlight glitch for issue edit form (bad selection item view).
For example, **Tags plugin**:
![image](https://user-images.githubusercontent.com/9638475/80355202-75193880-8880-11ea-811f-fdb96688d972.png)

The same bug for CRM, product plugin.

**Comment by mrliptontea** [comment]
Hmm I cannot replicate that

![Tags dropdown](https://user-images.githubusercontent.com/3495587/80534201-c3206000-8996-11ea-80b4-510a5c3a341a.png)

Did you customize anything in the theme?

**Comment by yurmala** [comment]
The same glitch with default theme. Sorry, friend!
I found it. This glitch happened after redmine_dmsf plugin installation.

**Comment by yurmala** [comment]
Glitch fixed with redmine_dmsf devel-2.4.3 version.
