### ISSUE TITLE
Possible to correctly format application.css?

### ISSUE THREAD

**Issue by WreckWren** [mrliptontea/PurpleMine2#188]
Having everything in the document in a single line is extremely inconvenient, to say the least.

**Comment by mrliptontea** [comment]
Hi,

application.css is built from source written in [SCSS](https://sass-lang.com/), it's not meant to be edited. But it's minimized so it loads a little faster (a file is a few KBs smaller than if it was formatted).

If you want to edit the theme, its source is here: https://github.com/mrliptontea/PurpleMine2/tree/master/src/sass
