### ISSUE TITLE
Integration with redmine_banner plugin ?

### ISSUE THREAD

**Issue by rroblik** [mrliptontea/PurpleMine2#189]
Hi,

Good job for this theme I'm loving it ! 
Do you think you can provide "out of the box" [redmine_banner](https://github.com/akiko-pusu/redmine_banner) plugin compatibility ? (the ugly !)

Thanks

**Comment by mrliptontea** [comment]
Hi,

See the release [v2.11.0](https://github.com/mrliptontea/PurpleMine2/releases/tag/v2.11.0) 😄
