### ISSUE TITLE
Issue list fields width and horizontal scroll

### ISSUE THREAD

**Issue by lublasco** [mrliptontea/PurpleMine2#19]
Hi,

in issue lists, when there are several columns with long text custom fields these columns are shown in a way that is not userfriendly (IMHO). You wan't see all columns in the same screen and have to horizontal scroll to see the next columns.

I attach two screenshots: one with PurpleMine2 and the second with Circle theme, so that you can see the difference. How can I achieve the Circle list layout (all columns in the same screen without horizontal scroll)?

![purplemine](https://cloud.githubusercontent.com/assets/6445323/11528089/df460b10-98e4-11e5-8683-66ddbdb921e8.JPG)

![circle](https://cloud.githubusercontent.com/assets/6445323/11528094/e6dfb3c6-98e4-11e5-8d1a-c5029614349a.JPG)

Thanks in advance for your help!

**Comment by mrliptontea** [comment]
Hmm after some investigation I ascertained that this is a bug - thank you for finding it!

**Comment by lublasco** [comment]
Thank you very much for the quick workaround! Just one more detail: the "Assigned to" field is maintaining the old width, so it keeps pushing the list to the right. How can I change it to achieve the Circle view for this field?

Thank you very much!

**Comment by mrliptontea** [comment]
I would prefer to leave "assigned to" column as it is, i.e. non-wrapping.
For your needs you can add the following style to
[_custom-variables.scss](/mrliptontea/PurpleMine2#how-to-customize-it):

```sass
tr.issue .assigned_to {
    white-space: normal;
}
```

**Comment by mrliptontea** [comment]
I would prefer to leave "assigned to" column as it is, i.e. non-wrapping.
For your needs you can add the following style to [_custom-variables.scss](/mrliptontea/PurpleMine2#how-to-customize-it):

```sass
tr.issue .assigned_to {
    white-space: normal;
}
```

**Comment by lublasco** [comment]
Thanks a lot!
