### ISSUE TITLE
Missing dynamic width & limit for custom fields (list format) with a large number of values.

### ISSUE THREAD

**Issue by kty0mka** [mrliptontea/PurpleMine2#196]
When using the standard themes (Alternate or Classic), column with list format custom fields are narrowed depending on the number of columns in the query.
When using Purple Mine, such columns do not have a width limit...

<img width="1375" alt="PurpleMine Scrol" src="https://user-images.githubusercontent.com/57333179/84683597-1d25b680-af40-11ea-8b06-ed468b461b09.png">

**Comment by mrliptontea** [comment]
Hi,

This should be fixed now, please pull the latest theme on master branch and [hard refresh](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) or restart Redmine server to see the changes.

**Comment by kty0mka** [comment]
Hi, @mrliptontea

Lightning fast)
Yes, now everything looks great.
Thank!
