### ISSUE TITLE
Bug in contextual issues navigation

### ISSUE THREAD

**Issue by alecghica** [mrliptontea/PurpleMine2#198]
How to reproduce:

- create a project with several sub-projects
- add issues in each project
- view an issue and click on the contextual navigation (upper right corner)
- you will notice the number of items found between prev and next will display a wrong number or the hole contextual box is missing during navigation

I used a **Redmine** version **4.1.1** and **PurpleMine2** version **2.11.0**.

**Comment by mrliptontea** [comment]
Hi,

Do you mean the `« Previous` and `Next »` links in this section?

![issue-pagination](https://user-images.githubusercontent.com/3495587/84804475-bd401600-affa-11ea-8803-40d8baf811aa.png)

I believe this uses session based on your most recent query on the issue list. If you need to keep navigating around projects and their issues list it might change or disappear, it's intended and is implemented in Redmine, this repository is just a theme 😉

**Comment by alecghica** [comment]
@mrliptontea Hi! I know, the strange thing is that when I enable the **PurpleMine2** theme navigation start to behave wrong. When I change back to a Classic theme or so it start to work fine.

**Comment by mrliptontea** [comment]
There's nothing I could fix about it in PurpleMine. I can reproduce this with the default theme:

1. Go to the issues list for all projects.
2. Click on an issue to view it, notice the pagination bar.
3. In a separate tab, go to the issues list for a different project than issues from 2.
4. Return back to the issue view from 2. and refresh - notice the pagination bar disappears.

**Comment by alecghica** [comment]
@mrliptontea Thx for your time! I'll let you know if I'll find something! :)

**Comment by alecghica** [comment]
@mrliptontea agree! My bad!

... just for the reference as I spent some time debugging it. :)

**Comment by mrliptontea** [comment]
No problem, glad you worked it out
