### ISSUE TITLE
[Suggestion] About default tab on issues-view page

### ISSUE THREAD

**Issue by drakosu** [mrliptontea/PurpleMine2#216]
Having "Notes" as default tab may be more user-oriented.

![image](https://user-images.githubusercontent.com/37822312/100202473-52e1b900-2f3c-11eb-8cea-574d536ea64f.png)

Take my company as example,
Changes to issue are just garbage information to end-user such as customers and engineers (and even product managers), because they are focusing on communications.
Supervisor may in few scenarios check issue changes.
Changes only matter to software manager and Redmine administrator.

I am posting it here because I have no JAVA skill. It take me some time to hardcode each time updating Purplemine2 to latest.

**Comment by mrliptontea** [comment]
Hi!

This is a good suggestion, however, these tabs are now supported by Redmine itself since version 4.1: https://www.redmine.org/news/127. And it defaults to displaying just Notes when they're available.

Is it possible for you to upgrade to the latest Redmine?

**Comment by drakosu** [comment]
Hello mrliptotea,

Thanks for your time checking this suggestion and sharing Redmine 4.1 info.

Redmine 4.1 looks fancy. I am currently using 3.2 and do have plan to update it, although updating plugins is expectably time-consuming. I will keep hardcoding until that happens.
