### ISSUE TITLE
[FEATURE] Provide the same highliting that is implementend in issue-comment also in issue-attachment-description

### ISSUE THREAD

**Issue by pasqualedante** [mrliptontea/PurpleMine2#218]
I attach a screenshot for clarity.
Thanks in advance.

<img width="919" alt="Immagine" src="https://user-images.githubusercontent.com/813690/103919467-59a14580-5110-11eb-9be8-e1ee07f5fc3f.png">

**Comment by mrliptontea** [comment]
Hi,

You need to request that as a feature in Redmine - attachment description doesn't support any rich formatting. There's nothing a theme can do about it.
