### ISSUE TITLE
dmsf plugin version 1.55 doesn't show some option in the files

### ISSUE THREAD

**Issue by armandoazcano** [mrliptontea/PurpleMine2#22]
We have found one issue

Vers. redmine 3.2.0, DMSF 1.5.5, and the last Purplemine2 

When you go to DMSF the folders work properly, but the files not work fine.
You can upload, and delete, but no more options are showed (modify, lock ... ).

I attached 

default theme  theme ( You can see all the folders and files correctly)

![working default theme ok](https://cloud.githubusercontent.com/assets/10224056/11869532/e62591c0-a4c0-11e5-9d73-78a1221fdf1c.jpg)

purplemine2 theme ( the folder are fine, but the files only have the delete option(1)(2))

![no working purplemine2 theme ok](https://cloud.githubusercontent.com/assets/10224056/11869536/ec28be9e-a4c0-11e5-9246-91b3aae219a1.jpg)

**Comment by njrover** [comment]
We had the same issue with the prior version of Redmine as well... my hack fix was to modify dmsf.css and add:

<pre>
.file .buttons>a img {
    display:inline !important;
}

.file .buttons>a[data-method="delete"]:before {
    content:"" !important;
}
</pre>

which appears to work in the latest Redmine/PurpleMine as well

I'm sure mrliptontea can likely find cleaner solution though.

**Comment by armandoazcano** [comment]
I modified dmsf.css and it looks fine.

Now all the file options are showed properly.

Thx for your help :-)

**Comment by mrliptontea** [comment]
I will try and find some nice, clean solution for this, but not before Christmas :christmas_tree:

**Comment by mrliptontea** [comment]
Sorry, it's been quite a while, over two Christmases later 😄 
I think the problem has been resolved somewhere along the way.
