### ISSUE TITLE
Adjustment of blocks in Project-Dashboard

### ISSUE THREAD

**Issue by kingharold1st** [mrliptontea/PurpleMine2#222]
It is cumbersome to move the blocks in the project dashboard. To put blocks in the 2-colum area is impossible.
When changing to default theme, everything works fine and the blocks can be adjusted easily also in the 2-column area.

**Comment by mrliptontea** [comment]
Hi,

Can you please include some screenshots of the area where you experience the issue?
The only page where I'm aware you can drag and drop is "My page" and I can move blocks there without any problem.

**Comment by kingharold1st** [comment]
Hi,
thank you for your reply.
On "My Page" the drag and drop works flawless.
I experience the problems at the project overview page(
/projects/<project-name> ). There one can add and arrange blocks with
information.
I attached screenshots.

Greetings
Martin


Am So., 23. Mai 2021 um 22:04 Uhr schrieb Grzegorz Rajchman <
***@***.***>:

**Comment by mrliptontea** [comment]
Hi,

The screenshots didn't come through to GitHub. I don't seem to be able to drag and drop on the project overview page, so I'm thinking a plugin is enabling that? Can you post the information from `/admin/info`, especially your plugin list?

**Comment by kingharold1st** [comment]
Hi,

please find the plugin list attached and thank you very much for your help
and the very beatiful redmine theme.

greetings
Martin

Am Mo., 31. Mai 2021 um 13:51 Uhr schrieb Grzegorz Rajchman <
***@***.***>:

**Comment by kingharold1st** [comment]
Sorry,

i attached schrenshots again.
here is the info as text:

Information

*Redmine 4.1.3.stable.20995*
Default administrator account changed
Attachments directory writable
Plugin assets directory writable (./public/plugin_assets)
MiniMagick available (optional)
ImageMagick convert available (optional)
ImageMagick PDF support available (optional)
System info : Linux redmine2 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1
(2020-04-27) x86_64 GNU/Linux
Uptime : 13 days

Environment:
  Redmine version                4.1.3.stable.20995
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem
Redmine plugins:
  additionals                    3.0.0
  custom_tables                  1.0.6
  redmine_base_deface            1.5.3
  redmine_base_stimulusjs        1.1.1
  redmine_checklists             3.1.16
  redmine_custom_reminder        0.7.2.ab6adfe
  redmine_custom_workflows       1.0.5
  redmine_dashboard              2.7.1
  redmine_dmsf                   2.4.5
  redmine_indicator              0.2.16
  redmine_issue_badge            0.1.4
  redmine_issue_templates        1.1.0
  redmine_issue_todo_lists       1.3
  redmine_multiprojects_issue    4.1.1
  stopwatch                      0.1.0
  view_customize                 2.8.1
  wiki_link                      0.0.1


greetings

Martin


Am Di., 1. Juni 2021 um 07:59 Uhr schrieb Martin Berger <
***@***.***>:
