### ISSUE TITLE
docker version log review

### ISSUE THREAD

**Issue by koraykutanoglu** [mrliptontea/PurpleMine2#236]
Does readmine have a special directory for log in docker? If yes, which directory is it?

**Comment by fishermans** [comment]
Not sure if I've got you right. To view the Redmine log, type _docker logs -f  &lt;name of your Redmine container&gt;_.

But this question is out of scope for this PurpleMine2 theme project, isn't it?

**Comment by koraykutanoglu** [comment]
The problem I'm having is quite old and I don't remember the details. Again, thank you for the return.
