### ISSUE TITLE
CSS file stripped

### ISSUE THREAD

**Issue by danillonunes** [mrliptontea/PurpleMine2#24]
I'm not sure if this is an issue with this theme, or Redmine, or Rails. But since it doesn't happen with other themes, I'm reporting here.

I'm using Redmine 3.0.7 with Passenger from a Docker container. I installed the PurpleMine2 theme and it worked fine, then I was testing other themes and at some point the stylesheets from PurpleMine2 broke and I could never fix them again. The theme works fine except it looks like a site without any CSS. I downloaded the file from MYSITE/themes/PurpleMine2/stylesheets/application.css and it’s stripped to 11KB, instead of the 106KB expected. But the original file in the public/themes directory on the server is correct.

I was doing a lot of changes at once and I couldn't figure out what I did that make the change, but if you need I can send detailed report of how my site is configured and the plugins I'm using.

**Comment by mrliptontea** [comment]
I'm closing this for now; please reopen if you have any questions but it looks like environment specific issue so I'm afraid I wouldn't be able to help. Hope you solved this by now :wink:

**Comment by danillonunes** [comment]
Yep, I solved it.

At some point I got a plugin broken with Redmine 3.3.x, then I downgraded to 3.2.x and tested this theme again and then it worked.

**Comment by danillonunes** [comment]
Just a quick update to whoever have this problem too.

Turns out I had the bug again and I’ve found it’s caused by CloudFlare. Adding the rule to disable CloudFlare performance settings and bypass caching for the domain fixes it.

**Comment by kusmierz** [comment]
It is enough to turn off "Auto Minify" for CSS (either for whole domain or in `Page Rules`).
