### ISSUE TITLE
Redmine5.0: Header style does not apply on mobile

### ISSUE THREAD

**Issue by Khsmty** [mrliptontea/PurpleMine2#253]
![Screenshot_20220601_205154](https://user-images.githubusercontent.com/70151015/171398365-190e7ff7-0911-4cd5-8046-24100afa3844.jpg)

In Redmine5.0 environment, styles are not applied to the mobile version of the header.

**Comment by carlittoer** [comment]
Hello,

Is PurpleMine2 going to support Redmine 5.x ?

**Comment by msundin** [comment]
Not only on mobile. This also happens in a browser on an ordinary laptop/desktop when the browser window is small enough (responsive design) to make the "hamburger" menu appear on the right hand side at the top.
