### ISSUE TITLE
The calendar is not displaying properly in Redmine 5.1.

### ISSUE THREAD

**Issue by jaebokoh** [mrliptontea/PurpleMine2#268]
Redmine 5.1 has been newly released, but there's an issue where the calendar is not displaying correctly on the screen. I understand you might be very busy, but I would appreciate it if you could fix this.

<img width="1762" alt="image" src="https://github.com/mrliptontea/PurpleMine2/assets/109948984/661367d9-574f-4fec-99b4-d25b65394ba8">

**Comment by serhiyraskoley** [comment]
I have the same. Could you please fix it 😶‍🌫️
![image](https://github.com/mrliptontea/PurpleMine2/assets/22105624/ecec9170-05b8-46b0-b145-d4173ad7847f)

**Comment by cypx** [comment]
@serhiyraskoley I made a PR to fix it. You could use my fork https://github.com/cypx/PurpleMine2/tree/master as a workaround (or just copy `stylesheets/application.css` file from my repository).

@mrliptontea could you have a look at the PR?

**Comment by serhiyraskoley** [comment]
@cypx thank you very much.
