### ISSUE TITLE
Can't have Sass @import inside a conditional

### ISSUE THREAD

**Issue by maedi** [mrliptontea/PurpleMine2#30]
According to [this issue](https://github.com/sass/libsass/issues/1724#issuecomment-221883988) putting a SASS @import inside a conditional is not allowed (can only import plain CSS in conditional).

This is my error when compiling application.scss with Sass 3.4.21:
`Error: Import directives may not be used within control directives or mixins. on line 9 of .../src/sass/components/_icons.scss
`

**Comment by mrliptontea** [comment]
Oh no :confused: well, I guess I saw that coming, although it used to work.
The only solution I can think of now is to move that import to `application.scss`. Fortunately, browsers don't load external fonts until they are necessary.

@maedi: Would you like to create a PR with that change? Or if you have a better idea that's most welcome. I need help with supporting this project as I don't use Redmine anymore. :sweat:
