### ISSUE TITLE
Breadcrumbs Redmine Titles not correctly applied

### ISSUE THREAD

**Issue by pacoaguayo** [mrliptontea/PurpleMine2#34]
Thanks for your great theme. 
Really great!

Please, would you mind include in future revisions:  "a.root", "a.ancestor" and ".current-project" to PurpleMine2. This is the code with force new-line for current-project.  In classic Redmine theme this effect it is usual.

Thanks a lot !

Best regards.

`a.root{
    font-size: 18px;
    font-weight: normal;
}

a.ancestor{
    font-size: 18px;
    font-weight: normal;
}

.current-project{
    display: block;
}`

This will be the effect:
![breadcrumbs-root-ancestor-current-project_enhancement](https://cloud.githubusercontent.com/assets/3742746/16684978/465e030a-4508-11e6-835b-d0390130d057.jpg)

**Comment by mrliptontea** [comment]
Hi,

`.current-project` class was just introduced in Redmine 3.3, and not everyone has that long project names, so for compatibility, I had to do it differently, but should do the trick for most cases.
