### ISSUE TITLE
README missing a step

### ISSUE THREAD

**Issue by michellemark** [mrliptontea/PurpleMine2#36]
I found that things do not work right without also doing the following install step (missing from your README)

npm install grunt-sass

**Comment by mrliptontea** [comment]
Hi,

It is required in [package.json](https://github.com/mrliptontea/PurpleMine2/blob/4181c09b020132049062f314f3c222a578bfce66/package.json#L24) so it should be install when you run `npm install`.

Although it's a dev dependency so it will be omitted if you have `NODE_ENV` variable set to `production`.

**Comment by michellemark** [comment]
I have a small Redmine installation here, production is what I have... therefore your instructions didn't work for me, I don't know enough about the details to say why, just reporting, I'm sure I'm not the only one who doesn't find a use for anything other than the production Redmine.

**Comment by mrliptontea** [comment]
I see your point. And since anyone would only install node dependencies if they want to change something in the theme, I guess its dependencies can be moved to production.
