### ISSUE TITLE
Lack of images (Delete, Edit  etc.) / Translation 

### ISSUE THREAD

**Issue by abrochet** [mrliptontea/PurpleMine2#42]
Hi,
  
I have a problem with my team we cannot see images of deletion, modification etc. Do you have any idea of where this problem come from? 
 
![image](https://cloud.githubusercontent.com/assets/24960001/21721594/489052bc-d429-11e6-88dc-237b942534e3.png)

 

We have also modified the .js script to integrate the French translation but it does not work. Can you help me on the reason please? 
 
![image](https://cloud.githubusercontent.com/assets/24960001/21721610/562579f2-d429-11e6-80f1-a227bcc09757.png)
 
- PurpleMine2\src\javascripts\modules\HistoryTabs.js
- PurpleMine2\src\javascripts\modules\MenuCollapse.js
- PurpleMine2\src\javascripts\modules\SidebarTogglers.js

 ```
var PurpleMine = PurpleMine || {}

PurpleMine.SidebarToggler = (function () {
  'use strict'

  var instance
  var translations = {
    fr: {
      toggler: 'Réduire la barre latérale'
    },
    en: {
      toggler: 'Toggle sidebar'
    },
    pl: {
      toggler: 'Pokaż/ukryj panel boczny'
    }
  }

  function SidebarToggler () {
    if (instance) {
      return instance
    }

    instance = this

    this.sidebarVisible = true
    this.sidebarHiding = null
    this.$toggler = null
    this.$main = $('#main')
    this.$sidebar = $('#sidebar')
    this.lang = 'fr' // Modification par ABRO on force la langue à FR

    if (typeof translations[this.lang] === 'undefined') {
      this.lang = 'en'
    }
	
    this._ = translations[this.lang]

    // Fix issue with context menu position
    if (this.$main.css('position') === 'relative') {
      $('#context-menu').appendTo('#wrapper3')
    }

    handleSidebar()
  }
```

Thank you.

**Comment by mrliptontea** [comment]
Hi,

I need more information.

Missing icons:
* What version of Redmine do you have?
* Does this occur everywhere or only on specific pages? On the screenshot, I see some icons are visible.
* Do you use any plugins which might alter styling and break the icons?

Translations:
* Inspect the source, check what's the value in `<html lang="">` attribute
* In devtools console, paste `document.documentElement.lang` and see what it returns.

**Comment by abrochet** [comment]
Hello,

Thank you for your reply.
 
Missing icons:
_•	What version of Redmine do you have?
•	Do you use any plugins which might alter styling and break the icons?_
 
The information below (version of redmine / plugin ):
 
![image](https://cloud.githubusercontent.com/assets/24960001/21767449/9984d39e-d674-11e6-994e-55112ec893e4.png)

 
_•	Does this occur everywhere or only on specific pages? On the screenshot, I see some icons are visible._ 
For the moment the error has been detected on the edition page of tickets. (Adding Observer / editing comments / deleting comments etc.)

Translations:
_•	Inspect the source, check what's the value in `<html lang="">` attribute_
      I did not find any attribute:  `<html lang="">` sorry.

_•	In devtools console, paste document.documentElement.lang and see what it returns._
        Sorry how do I use the devtools console?

**Comment by mrliptontea** [comment]
Hi,

To open the devtools console in Google Chrome/Opera press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac). Then copy and paste said code and hit enter

![image](https://cloud.githubusercontent.com/assets/3495587/21768511/ee787e58-d671-11e6-99fa-017a2213ea7f.png)

**Comment by abrochet** [comment]
Ok, thanks.

The result:

![image](https://cloud.githubusercontent.com/assets/24960001/21769565/9d16c296-d67f-11e6-8955-080099e916e2.png)

Thank you for your help.

**Comment by mrliptontea** [comment]
Ok, so `fr` key in the code should work.
Did you run the following commands?
```
npm install grunt-cli -g
npm install
grunt
```

**Comment by abrochet** [comment]
No. The commands running under windows server?

**Comment by mrliptontea** [comment]
JavaScript is concatenated and minified. The file(s) you modified is not used directly in Redmine; you have to run `grunt` for your changes to take effect.
Please read https://github.com/mrliptontea/PurpleMine2#how-to-customize-it

Or you can just send me French translations; I'll be happy to add them.

**Comment by abrochet** [comment]
It's doesn't work, the result command:

![image](https://cloud.githubusercontent.com/assets/24960001/21783269/e34accf8-d6b6-11e6-8049-023aa1b6e017.png)

**The translations :**

**- File MenuCollapse.js**
   _topMenuToggler: 'Développer / réduire le menu principal'_

**- File HistoryTabs.js** 
   _all: 'Tout',
   notes: 'Commentaires',
   details: 'Changements'_

**- File SidebarToggler.js**
  _toggler: 'Réduire la barre latérale'_

I would like to be able to make it works myself because my team would also like to change the menu order : 
All / Notes / Changes to Notes / Changes / All

**Comment by mrliptontea** [comment]
The file was created, so it worked.
```
Running "uglify:theme" (uglify) task
>> 1 file created.
```

You can test in `C:\Test\PurpleMine2\javascripts\theme.js` if it contains your changes, e.g. by running
```
C:\Test\PurpleMine2> find "Changements" javascripts\theme.js
```

Now make sure that this file is uploaded to your Redmine server under
`[Redmine installation]/public/themes/PurpleMine2/javascripts/theme.js` path.

**Comment by abrochet** [comment]
It's good for me. Thank you very much :)

The images are not missing on our redmine version 3.2.0 we have the same plugins on both redmine. I think there is an incompatibility with version 3.3.0.

**Comment by mrliptontea** [comment]
Ha, you closed an issue when I finally got some time to check the icon problem.
I did few amends to force styles which were overridden by RM+ plugins, namely their `a_common_libs`.

**Comment by abrochet** [comment]
Hello,

We don’t have the problem on our two other redmine yet we have the same plugin. 
I ran a test with the 3.3 version of redmine I didn't encounter the problem anymore so we will migrate our 3 redmine to the latest version.
 
Thank you for your time.

By the way your plugin is really great.

**Comment by mrliptontea** [comment]
Thank you for your appreciation 😄

That's right because the `icon-only` class, which was overridden, was introduced in Redmine 3.3, and in earlier versions wasn't present anywhere in templates. Also, tabs styles were a little off with these plugins, so I made sure PurpleMine takes precedence.

**Comment by abrochet** [comment]
Hello,

I keep you informed of the migration of our Redmine. You were right the problem came from the a_commons-libs plugin. I identified the part of the code which was a problem.

`.icon-only {
  background-position: 0 50%;
  background-repeat: no-repeat;
  padding-left: 16px;
}
a.icon-only {
  display: inline-block;
  width: 0;
  height: 16px;
  overflow: hidden;
  padding-top: 0;
  padding-bottom: 0;
  font-size: 8px;
  vertical-align: text-bottom;
}
`

However we had to stop at the 3.3.2.stable.16261 version because in 3.3.3 version your theme has some problems.

When an update of your theme will be available it will be installed willingly but at the moment all the plugins are not yet compatible for version 3.3.3.

Best regards.

**Comment by mrliptontea** [comment]
Hi,

I don't really update this theme unless someone reports an issue as I don't use Redmine anymore.
Can you be more specific about what problems you experienced in? I didn't test it extensively but I haven't noticed anything being unusable in Redmine 3.3.
