### ISSUE TITLE
Issues page not aligned

### ISSUE THREAD

**Issue by Reborns** [mrliptontea/PurpleMine2#45]
Hi, The  issue page not looking good because of alignment left
I thnk this can be aligned to center , 
Here is a 2 screenshots to compare 
**Aligned**
![aligned](https://cloud.githubusercontent.com/assets/10342482/23340900/d00fb48e-fc57-11e6-88fd-97d3bc2b3e62.png)

**Not Aligned** 
![not_aligned](https://cloud.githubusercontent.com/assets/10342482/23340902/df889476-fc57-11e6-9e13-8ca69d104735.png)

**Comment by mrliptontea** [comment]
Hi,

Thank you for your feedback. I agree that content would look better if was aligned with the headers but I don't agree it would be better centered, a text is generally more readable if left-aligned. There are also some numeric columns which are aligned to the right.

See example:
![issues](https://cloud.githubusercontent.com/assets/3495587/23341104/6df9ab42-fc39-11e6-9cde-d6797b59187d.png)

Unfortunately, Redmine doesn't provide the same classes for the headers, so I cannot align them with table body 😞

**Comment by Reborns** [comment]
Yes i agree ... by the way , This is a best theme for Redmine i ever saw . THANK YOU VERT MUCH !!!
