### ISSUE TITLE
Add font Awesome icons to #top-menu

### ISSUE THREAD

**Issue by Reborns** [mrliptontea/PurpleMine2#46]
This is a enhancement request .. Pease add  font Awesome icons to #top-menu

**Example** 
![fa_icons](https://cloud.githubusercontent.com/assets/10342482/23341116/2e3605ec-fc5b-11e6-9cb0-3bbc4ca3dded.png)

**Comment by mrliptontea** [comment]
Hi,

I did consider this a while ago, although I decided not to because plugins often add links to that menu and it looks weird when some options are missing an icon.

But I am open to receive a Pull Request if you believe it's worth it 😉
