### ISSUE TITLE
Support Redmine Git Hosting

### ISSUE THREAD

**Issue by ghost** [mrliptontea/PurpleMine2#47]
Hi, 
I read in README that your theme is compatible with some plugins ... 
i would like recomend to have a look at this plugin for  Redmine https://github.com/jbox-web/redmine_git_hosting. And if it will possible make this plugin looks better in your theme .. 

Thanks

**Comment by mrliptontea** [comment]
Hi,

I didn't setup the plugin fully, but at first glance, I would say that it looks pretty good to me. Do you have any particular page in mind that needs improvement?

**Comment by Reborns** [comment]
Hi, :) 
root page of repo needs to be polished 
https://red.reborns.info/projects/public/repository 
i marked main differences on the screenshot 
![untitled](https://cloud.githubusercontent.com/assets/10342482/23390265/6d0e57a2-fd86-11e6-8c8a-1c2f7b1bc16c.png)

If you need access to dig a bit more ,  just ask about it..

**Comment by mrliptontea** [comment]
I'll close this now. If there's still interest in this, let me know here.
