### ISSUE TITLE
Chrome: unable to sort by drag-and-drop

### ISSUE THREAD

**Issue by k-mack** [mrliptontea/PurpleMine2#48]
### Setup

* Chrome 56.0.2924.87
* Redmine 3.3.2

### Repeat

* Login as admin
* Navigate to Administration -> Issue Statuses
* Click green verticle bi-directional arrow
* Attempt to drag and drop status into new position in the list

This problem exists for other areas where drag-and-drop sorting is used.

### Workaround

* Use Firefox 51.0.1
* Use IE 11

**Comment by Reborns** [comment]
Hmm , this is strange , cos it`s working for me . Chrome 56.0.2924.87

**Comment by k-mack** [comment]
Chrome's Developer Tools shows the follow errors when I navigate to pages with this drag-and-drop sorting functionality. On the Administration page, I first navigated to the Issue Statues page, then to the Trackers page. Below is a screen-capture of the browser's console:

![image](https://cloud.githubusercontent.com/assets/2957142/23562940/92246246-0012-11e7-97b3-d98bf1e689d8.png)

For the Trackers page, the place of the error in the HTML is:

``` html
 <script>
//<![CDATA[

  $(function() { $("table.trackers tbody").positionedItems(); });

//]]>

</script>
```

Firefox shows no errors in its console when I navigate to those same pages.

It's odd that we have the same versions of Chrome but are having different user experiences.

**Comment by k-mack** [comment]
FYI, my environment copied out of the Information page of Redmine is:

```
Environment:
  Redmine version                3.3.2.stable
  Ruby version                   2.1.9-p490 (2016-03-30) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.8.8
  Darcs                          2.8.4
  Mercurial                      2.8.2
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.2
  redmine_checklists             3.1.3
  redmine_monitoring_controlling 0.1.1
```

**Comment by Reborns** [comment]
OK i see . you have issues , but i think this issues is not related to this theme. or any other theme ...

**Comment by k-mack** [comment]
I just tried to do this on my other laptop that is running Chrome 56.0.2924.76 and everything worked as expected. This issue isn't related to your plugin.

**Comment by mrliptontea** [comment]
This might be caused by a browser plugin, e.g. an ad blocker or something like that.

**Comment by k-mack** [comment]
Just in case anyone encounters this, refreshing the cache on that (Ctrl + F5) solved the issue.
