### ISSUE TITLE
Anchors won't scroll the page

### ISSUE THREAD

**Issue by BenoitDuffez** [mrliptontea/PurpleMine2#62]
On a wiki page with several `h1.`, `h2.` etc tags, and with a `{{toc}}` at the begining of the page, the links to the titles won't work.

The URL is properly appended with `#anchor_name`, the anchor exists in the DOM but the browser doesn't scroll.

When manually scrolling, the _#_ is highlighted though. So half of the job is done :)

Tested on latest stable Chrome on Linux with no extension loaded.

**Comment by BenoitDuffez** [comment]
Note: removing this from the DOM fixes the issue, so that comes from it:

    <link rel="stylesheet" media="all" href="/themes/PurpleMine2-master/stylesheets/application.css">

**Comment by BenoitDuffez** [comment]
It looks like it is because of the `overflow` property of that selector:

```css
.wiki.wiki-page a[name]:empty {
    display: block;
    overflow: hidden
}
```

**Comment by BenoitDuffez** [comment]
Actually, both properties are required to reproduce this bug, e.g. removing either one fixes the behavior (but creates an empty spacer before each header title).

Removing both properties and replacing them with `float: left` makes the link behave properly _and_ does not add an empty spacer.

I don't know anything about how you compiled the CSS so I won't be able to submit a PR. However I hope this helps finding the root cause and maybe fix this issue if I am not the only one impacted.

Cheers!

**Comment by halfjust** [comment]
+1
