### ISSUE TITLE
buttons are messed up in Issue at Notes section

### ISSUE THREAD

**Issue by BigOHenry** [mrliptontea/PurpleMine2#86]
Hello, 
i found a messed up buttons at existing notes (comments) in a issue.
![redmine](https://user-images.githubusercontent.com/15823552/54198159-151dd200-44c6-11e9-8b49-d87c042c1c7b.png)

The icon with bin is edit button. etc.
Redmine version is 4.0

Can you reproduce that please?

**Comment by mrliptontea** [comment]
Check the latest release 😉

**Comment by BigOHenry** [comment]
Its fixed :) Thank you very much. btw v2.0 is amazing :)
