### ISSUE TITLE
feature collapse subproject

### ISSUE THREAD

**Issue by cowrycoin** [mrliptontea/PurpleMine2#88]
Hi, could you add the option to collapse subprojects in the overview of all projects?

**Comment by mrliptontea** [comment]
Hi,

Can you please try this plugin https://github.com/anton-sergeev/redmine_subproject_collapse?

**Comment by cowrycoin** [comment]
Ok, it works. This is not perfect, as the plugin doesn't remember if collapsed or not. If you refresh the page, it is all uncollapse again. But it works! Maybe I should contact for this anton-sergeev

Thanks for your recommendation!
