### ISSUE TITLE
layout is off and most links not clickable after changing to purplemine2 theme.

### ISSUE THREAD

**Issue by smetis** [mrliptontea/PurpleMine2#89]
Hi,
I downloaded the latest theme V2.0 and apply it. After that the redmine layout if way off and most links are not clickable. My redmine is installed via bitnami redmine+agile. I am not sure if this has anything to do with bitnami or browser settings? 

Details:
======
Browser tested: chrome and firefox. Both not working.

**Comment by mrliptontea** [comment]
I tested it with [Agile plugin](https://www.redmine.org/plugins/redmine_agile) on Redmine 3.0, 3.4, and 4.0 and no issues on Chrome, Firefox, and Edge.

Try inspecting a few links with browser dev tools (right click on the element, click inspect), see which on what element click ends up landing and where its CSS is coming from. Screenshots would be useful, also see if you have any other plugin apart from Agile.

**Comment by smetis** [comment]
I did a fresh install and the theme works as expected. I have many other plugins and i guess one of it messed up the layout of themes. So this definitely not purplemine2 theme issue. I will close this. Thanks for taking time to verify.

**Comment by smetis** [comment]
sorry to reopen this again, i found that after installing [custom menu](http://rmplus.pro/en/redmine/plugins/custom_menu) plugin from rmplus.pro, it breaks purplemine2 theme. 

Initially I thought the plugin is broken, but after I realized other themes like "[A1](https://www.redmineup.com/pages/themes/a1)", "[Circle](https://www.redmineup.com/pages/themes/circle)", "[Coffee](https://www.redmineup.com/pages/themes/coffee)" and "[yh redmine theme](https://github.com/yenihayat/redmine-theme-yh)" all works without issue, I figured I should reopen this , maybe you can help to shed some light on why purplemine2 isn't. 

The closest modern theme similar to purplemine2 is "redmine-theme-yh" but still, i personally prefer purplemine2 theme if it is working. 

not working with purplemine2 (all links are not clickable after apply the theme):
![image](https://user-images.githubusercontent.com/6990404/54643724-d69f8e80-4a54-11e9-90fb-250b1161e488.png)


working with yh theme:
![image](https://user-images.githubusercontent.com/6990404/54643498-45c8b300-4a54-11e9-90c5-061b5ea19c90.png)

**Comment by mrliptontea** [comment]
Ah, good spot, now I can investigate it 👍

**Comment by mrliptontea** [comment]
@smetis Please check 97b68972f7c20ef155b47ffa4399db9ce2e08ef7 or the `issue-89-custom-menu-plugin-breaks-layout` branch and see if it resolves all issues

**Comment by smetis** [comment]
@mrliptontea this branch works well with the plugins, appreciate your superb fast response. I think we can close this and merge into master.
