### ISSUE TITLE
Subtasks formatting is off

### ISSUE THREAD

**Issue by pbystrov** [mrliptontea/PurpleMine2#94]
Structure of tasks and sub-tasks is almost flat and it is hard to distinguish levels below.

PurpleMine2 —
![subtasks-1](https://i.snag.gy/Jajx54.jpg)
Another theme —
![subtasks-2](https://i.snag.gy/BhesQF.jpg)

**Comment by mrliptontea** [comment]
Hi, thanks for reporting this.

See `issue-94-subtasks-formatting-is-off` branch for a fix.

**Comment by pbystrov** [comment]
Looking good, thank you

**Comment by guillermoml** [comment]
I had done some manual hacks to achieve this kind of indentation, but this is way better.
These changes will be backported to 1.X branch?

Thanks for this theme

**Comment by mrliptontea** [comment]
@guillermoml I released v1.11 with some of the fixes made recently in v2, available on the v1.x branch.
